mysql:
  host: localhost
  username: root
  password: ${MYSQL_ROOT_PASSWORD}
  maxIdleConns: 20
  maxOpenConns: 200
  maxLifetimeSec: 7200
redis:
  host: localhost
  password: ${REDIS_PASSWORD}
gcs:
  bucketname: meeting-center-storage-test