mysql:
    host: localhost
    username: root
    password: ${MYSQL_ROOT_PASSWORD}
    maxIdleConns: 10
    maxOpenConns: 100
    maxLifetimeSec: 3600
redis:
    host: localhost
    password: ${REDIS_PASSWORD}
gcs:
    bucketname: meeting-center-storage-prod
mail:
    apiKey: ${SENDGRID_API_KEY}
