mysql:
  host: db
  username: root
  password: ${MYSQL_ROOT_PASSWORD}
  maxIdleConns: 10
  maxOpenConns: 100
  maxLifetimeSec: 3600
redis:
  host: redis
  password: ${REDIS_PASSWORD}
gcs:
  bucketname: meeting-center-storage-prod