definitions:
  models.CodeType:
    properties:
      code_values:
        items:
          $ref: '#/definitions/models.CodeValue'
        type: array
      id:
        type: integer
      type_desc:
        type: string
      type_name:
        type: string
    type: object
  models.CodeValue:
    properties:
      code_type_id:
        type: integer
      code_value:
        type: string
      code_value_desc:
        type: string
      id:
        type: integer
    type: object
  models.User:
    properties:
      created_at:
        type: string
      email:
        type: string
      id:
        type: integer
      password:
        type: string
      role:
        type: string
      updated_at:
        type: string
      username:
        type: string
    type: object
  presentations.CreateCodeTypeParam:
    properties:
      type_desc:
        type: string
      type_name:
        type: string
    required:
    - type_desc
    - type_name
    type: object
  presentations.CreateCodeTypeResponse:
    properties:
      data:
        properties:
          code_type:
            properties:
              code_values:
                items:
                  $ref: '#/definitions/models.CodeValue'
                type: array
              id:
                type: integer
              type_desc:
                type: string
              type_name:
                type: string
            type: object
        type: object
      message:
        type: string
      status:
        type: string
    type: object
  presentations.CreateCodeValueParam:
    properties:
      code_type_id:
        type: integer
      code_value:
        type: string
      code_value_desc:
        type: string
    required:
    - code_type_id
    - code_value
    - code_value_desc
    type: object
  presentations.CreateCodeValueResponse:
    properties:
      data:
        properties:
          code_value:
            properties:
              code_type_id:
                type: integer
              code_value:
                type: string
              code_value_desc:
                type: string
              id:
                type: integer
            type: object
        type: object
      message:
        type: string
      status:
        type: string
    type: object
  presentations.DeleteCodeTypeResponse:
    properties:
      data:
        type: object
      message:
        type: string
      status:
        type: string
    type: object
  presentations.DeleteCodeValueResponse:
    properties:
      data:
        type: object
      message:
        type: string
      status:
        type: string
    type: object
  presentations.GetAllCodeTypesResponse:
    properties:
      data:
        properties:
          code_types:
            items:
              $ref: '#/definitions/models.CodeType'
            type: array
        type: object
      message:
        type: string
      status:
        type: string
    type: object
  presentations.LoginParams:
    properties:
      email:
        type: string
      password:
        type: string
    type: object
  presentations.LoginResponse:
    properties:
      data:
        properties:
          message:
            type: string
          token:
            type: string
          user:
            properties:
              created_at:
                type: string
              email:
                type: string
              id:
                type: integer
              role:
                type: string
              updated_at:
                type: string
              username:
                type: string
            type: object
        type: object
      status:
        type: string
    type: object
  presentations.LogoutResponse:
    properties:
      data:
        properties:
          message:
            type: string
        type: object
      status:
        type: string
    type: object
  presentations.UpdateCodeTypeParam:
    properties:
      id:
        type: integer
      type_desc:
        type: string
      type_name:
        type: string
    required:
    - id
    - type_desc
    - type_name
    type: object
  presentations.UpdateCodeTypeResponse:
    properties:
      data:
        properties:
          code_type:
            $ref: '#/definitions/models.CodeType'
        type: object
      message:
        type: string
      status:
        type: string
    type: object
  presentations.UpdateCodeValueParam:
    properties:
      code_type_id:
        type: integer
      code_value:
        type: string
      code_value_desc:
        type: string
      id:
        type: integer
    required:
    - code_type_id
    - code_value
    - code_value_desc
    - id
    type: object
  presentations.UpdateCodeValueResponse:
    properties:
      data:
        properties:
          code_value:
            properties:
              code_type_id:
                type: integer
              code_value:
                type: string
              code_value_desc:
                type: string
              id:
                type: integer
            type: object
        type: object
      message:
        type: string
      status:
        type: string
    type: object
  presentations.WhoAmIResponse:
    properties:
      data:
        properties:
          user:
            properties:
              id:
                type: integer
            type: object
        type: object
      message:
        type: string
      status:
        type: string
    type: object
info:
  contact: {}
  description: This is a simple Meeting Center API
  title: Meeting Center API
  version: "1.0"
paths:
  /auth/login:
    post:
      consumes:
      - application/json
      description: Login a user
      parameters:
      - description: User object
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/presentations.LoginParams'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/presentations.LoginResponse'
      summary: Login a user
      tags:
      - Auth
  /auth/logout:
    post:
      consumes:
      - application/json
      description: Logout a user
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/presentations.LogoutResponse'
      summary: Logout a user
      tags:
      - Auth
  /auth/whoami:
    get:
      consumes:
      - application/json
      description: Get the user who is logged in
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/presentations.WhoAmIResponse'
      summary: Get the user who is logged in
      tags:
      - Auth
  /code/type:
    delete:
      consumes:
      - application/json
      description: Delete a code type
      parameters:
      - description: CodeType ID
        in: query
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/presentations.DeleteCodeTypeResponse'
      summary: Delete a code type
      tags:
      - code
    post:
      consumes:
      - application/json
      description: Create a new code type
      parameters:
      - description: CodeType
        in: body
        name: codeType
        required: true
        schema:
          $ref: '#/definitions/presentations.CreateCodeTypeParam'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/presentations.CreateCodeTypeResponse'
      summary: Create a new code type
      tags:
      - code
    put:
      consumes:
      - application/json
      description: Update a code type
      parameters:
      - description: CodeType
        in: body
        name: codeType
        required: true
        schema:
          $ref: '#/definitions/presentations.UpdateCodeTypeParam'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/presentations.UpdateCodeTypeResponse'
      summary: Update a code type
      tags:
      - code
  /code/type/getAllCodeTypes:
    get:
      consumes:
      - application/json
      description: Get all code types
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/presentations.GetAllCodeTypesResponse'
      summary: Get all code types
      tags:
      - code
  /code/value:
    delete:
      consumes:
      - application/json
      description: Delete a code value
      parameters:
      - description: CodeValue ID
        in: query
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/presentations.DeleteCodeValueResponse'
      summary: Delete a code value
      tags:
      - code
    post:
      consumes:
      - application/json
      description: Create a new code value
      parameters:
      - description: CodeValue
        in: body
        name: codeValue
        required: true
        schema:
          $ref: '#/definitions/presentations.CreateCodeValueParam'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/presentations.CreateCodeValueResponse'
      summary: Create a new code value
      tags:
      - code
    put:
      consumes:
      - application/json
      description: Update a code value
      parameters:
      - description: CodeValue
        in: body
        name: codeValue
        required: true
        schema:
          $ref: '#/definitions/presentations.UpdateCodeValueParam'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/presentations.UpdateCodeValueResponse'
      summary: Update a code value
      tags:
      - code
  /user:
    post:
      consumes:
      - application/json
      description: Register a new user
      parameters:
      - description: User object
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/models.User'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.User'
      summary: Register a new user
      tags:
      - User
    put:
      consumes:
      - application/json
      description: Update user
      parameters:
      - description: User object
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/models.User'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.User'
      summary: Update user
      tags:
      - User
swagger: "2.0"
